<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipalitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('municipalities')->insert([
            ['name'=>'Acacoyagua','key'=>'001'],
            ['name'=>'Acala','key'=> '002' ],
            ['name'=>'Acapetahua','key'=> '003' ],
            ['name'=>'Altamirano','key'=> '004' ],
            ['name'=>'Amatán','key'=> '005' ],
            ['name'=>'Amatenango de la Frontera','key'=> '006' ],
            ['name'=>'Amatenango del Valle','key'=> '007' ],
            ['name'=>'Ángel Albino Corzo','key'=> '008' ],
            ['name'=>'Arriaga','key'=> '009' ],
            ['name'=>'Bejucal de Ocampo','key'=> '010' ],
            ['name'=>'Bella Vista','key'=> '011' ],
            ['name'=>'Berriozábal','key'=> '012' ],
            ['name'=>'Bochil','key'=> '013' ],
            ['name'=>'El Bosque','key'=> '014' ],
            ['name'=>'Cacahoatán','key'=> '015' ],
            ['name'=>'Catazajá','key'=> '016' ],
            ['name'=>'Cintalapa','key'=> '017' ],
            ['name'=>'Coapilla','key'=> '018' ],
            ['name'=>'Comitán de Domínguez','key'=> '019' ],
            ['name'=>'La Concordia','key'=> '020' ],
            ['name'=>'Copainalá','key'=> '021' ],
            ['name'=>'Chalchihuitán','key'=> '022' ],
            ['name'=>'Chamula','key'=> '023' ],
            ['name'=>'Chanal','key'=> '024' ],
            ['name'=>'Chapultenango','key'=> '025' ],
            ['name'=>'Chenalhó','key'=> '026' ],
            ['name'=>'Chiapa de Corzo','key'=> '027' ],
            ['name'=>'Chiapilla','key'=> '028' ],
            ['name'=>'Chicoasén','key'=> '029' ],
            ['name'=>'Chicomuselo','key'=> '030' ],
            ['name'=>'Chilón','key'=> '031' ],
            ['name'=>'Escuintla','key'=> '032' ],
            ['name'=>'Francisco León','key'=> '033' ],
            ['name'=>'Frontera Comalapa','key'=> '034' ],
            ['name'=>'Frontera Hidalgo','key'=> '035' ],
            ['name'=>'La Grandeza','key'=> '036' ],
            ['name'=>'Huehuetán','key'=> '037' ],
            ['name'=>'Huixtán','key'=> '038' ],
            ['name'=>'Huitiupán','key'=> '039' ],
            ['name'=>'Huixtla','key'=> '040' ],
            ['name'=>'La Independencia','key'=> '041' ],
            ['name'=>'Ixhuatán','key'=> '042' ],
            ['name'=>'Ixtacomitán','key'=> '043' ],
            ['name'=>'Ixtapa','key'=> '044' ],
            ['name'=>'Ixtapangajoya','key'=> '045' ],
            ['name'=>'Jiquipilas','key'=> '046' ],
            ['name'=>'Jitotol','key'=> '047' ],
            ['name'=>'Juárez','key'=> '048' ],
            ['name'=>'Larráinzar','key'=> '049' ],
            ['name'=>'La Libertad','key'=> '050' ],
            ['name'=>'Mapastepec','key'=> '051' ],
            ['name'=>'Las Margaritas','key'=>'052' ],
            ['name'=>'Mazapa de Madero','key'=>'053' ],
            ['name'=>'Mazatán','key'=>'054' ],
            ['name'=>'Metapa','key'=>'055' ],
            ['name'=>'Mitontic','key'=>'056' ],
            ['name'=>'Motozintla','key'=>'057' ],
            ['name'=>'Nicolás Ruíz','key'=>'058' ],
            ['name'=>'Ocosingo','key'=>'059' ],
            ['name'=>'Ocotepec','key'=>'060' ],
            ['name'=>'Ocozocoautla de Espinosa','key'=>'061' ],
            ['name'=>'Ostuacán','key'=>'062' ],
            ['name'=>'Osumacinta','key'=>'063' ],
            ['name'=>'Oxchuc','key'=>'064' ],
            ['name'=>'Palenque','key'=>'065' ],
            ['name'=>'Pantelhó','key'=>'066' ],
            ['name'=>'Pantepec','key'=>'067' ],
            ['name'=>'Pichucalco','key'=>'068' ],
            ['name'=>'Pijijiapan','key'=>'069' ],
            ['name'=>'El Porvenir','key'=>'070' ],
            ['name'=>'Villa Comaltitlán','key'=>'071' ],
            ['name'=>'Pueblo Nuevo Solistahuacán','key'=>'072' ],
            ['name'=>'Rayón','key'=>'073' ],
            ['name'=>'Reforma','key'=>'074' ],
            ['name'=>'Las Rosas','key'=>'075' ],
            ['name'=>'Sabanilla','key'=>'076' ],
            ['name'=>'Salto de Agua','key'=>'077' ],
            ['name'=>'San Cristóbal de las Casas','key'=>'078' ],
            ['name'=>'San Fernando','key'=>'079' ],
            ['name'=>'Siltepec','key'=>'080' ],
            ['name'=>'Simojovel','key'=>'081' ],
            ['name'=>'Sitalá','key'=>'082' ],
            ['name'=>'Socoltenango','key'=>'083' ],
            ['name'=>'Solosuchiapa','key'=>'084' ],
            ['name'=>'Soyaló','key'=>'085' ],
            ['name'=>'Suchiapa','key'=>'086' ],
            ['name'=>'Suchiate','key'=>'087' ],
            ['name'=>'Sunuapa','key'=>'088' ],
            ['name'=>'Tapachula','key'=>'089' ],
            ['name'=>'Tapalapa','key'=>'090' ],
            ['name'=>'Tapilula','key'=>'091' ],
            ['name'=>'Tecpatán','key'=>'092' ],
            ['name'=>'Tenejapa','key'=>'093' ],
            ['name'=>'Teopisca','key'=>'094' ],
            ['name'=>'Tila','key'=>'095' ],
            ['name'=>'Tonalá','key'=>'096' ],
            ['name'=>'Totolapa','key'=>'097' ],
            ['name'=>'La Trinitaria','key'=>'098' ],
            ['name'=>'Tumbalá','key'=>'099' ],
            ['name'=>'Tuxtla Gutiérrez','key'=>'100' ],
            ['name'=>'Tuxtla Chico','key'=>'101' ],
            ['name'=>'Tuzantán','key'=>'102' ],
            ['name'=>'Tzimol','key'=>'103' ],
            ['name'=>'Unión Juárez','key'=>'104' ],
            ['name'=>'Venustiano Carranza','key'=>'105' ],
            ['name'=>'Villa Corzo','key'=>'106' ],
            ['name'=>'Villaflores','key'=>'107' ],
            ['name'=>'Yajalón','key'=>'108' ],
            ['name'=>'San Lucas','key'=>'109' ],
            ['name'=>'Zinacantán','key'=>'110' ],
            ['name'=>'San Juan Cancuc','key'=>'111' ],
            ['name'=>'Aldama','key'=>'112' ],
            ['name'=>'Benemérito de las Américas','key'=>'113' ],
            ['name'=>'Maravilla Tenejapa','key'=>'114' ],
            ['name'=>'Marqués de Comillas','key'=>'115' ],
            ['name'=>'Montecristo de Guerrero','key'=>'116' ],
            ['name'=>'San Andrés Duraznal','key'=>'117' ],
            ['name'=>'Santiago el Pinar','key'=>'118' ],
            ['name'=>'Capitán Luis Ángel Vidal','key'=>'119' ],
            ['name'=>'Rincón Chamula San Pedro','key'=>'120' ],
            ['name'=>'El Parral','key'=>'121' ],
            ['name'=>'Emiliano Zapata','key'=>'122' ],
            ['name'=>'Mezcalapa','key'=>'123' ],
            ['name'=>'Honduras de la Sierra','key'=>'124' ]
        ]);
    }
}
