<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipalitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('municipalities')->insert([
            ['nombre'=>'Acacoyagua','clave'=>'001'],
            ['nombre'=>'Acala','clave'=> '002' ],
            ['nombre'=>'Acapetahua','clave'=> '003' ],
            ['nombre'=>'Altamirano','clave'=> '004' ],
            ['nombre'=>'Amatán','clave'=> '005' ],
            ['nombre'=>'Amatenango de la Frontera','clave'=> '006' ],
            ['nombre'=>'Amatenango del Valle','clave'=> '007' ],
            ['nombre'=>'Ángel Albino Corzo','clave'=> '008' ],
            ['nombre'=>'Arriaga','clave'=> '009' ],
            ['nombre'=>'Bejucal de Ocampo','clave'=> '010' ],
            ['nombre'=>'Bella Vista','clave'=> '011' ],
            ['nombre'=>'Berriozábal','clave'=> '012' ],
            ['nombre'=>'Bochil','clave'=> '013' ],
            ['nombre'=>'El Bosque','clave'=> '014' ],
            ['nombre'=>'Cacahoatán','clave'=> '015' ],
            ['nombre'=>'Catazajá','clave'=> '016' ],
            ['nombre'=>'Cintalapa','clave'=> '017' ],
            ['nombre'=>'Coapilla','clave'=> '018' ],
            ['nombre'=>'Comitán de Domínguez','clave'=> '019' ],
            ['nombre'=>'La Concordia','clave'=> '020' ],
            ['nombre'=>'Copainalá','clave'=> '021' ],
            ['nombre'=>'Chalchihuitán','clave'=> '022' ],
            ['nombre'=>'Chamula','clave'=> '023' ],
            ['nombre'=>'Chanal','clave'=> '024' ],
            ['nombre'=>'Chapultenango','clave'=> '025' ],
            ['nombre'=>'Chenalhó','clave'=> '026' ],
            ['nombre'=>'Chiapa de Corzo','clave'=> '027' ],
            ['nombre'=>'Chiapilla','clave'=> '028' ],
            ['nombre'=>'Chicoasén','clave'=> '029' ],
            ['nombre'=>'Chicomuselo','clave'=> '030' ],
            ['nombre'=>'Chilón','clave'=> '031' ],
            ['nombre'=>'Escuintla','clave'=> '032' ],
            ['nombre'=>'Francisco León','clave'=> '033' ],
            ['nombre'=>'Frontera Comalapa','clave'=> '034' ],
            ['nombre'=>'Frontera Hidalgo','clave'=> '035' ],
            ['nombre'=>'La Grandeza','clave'=> '036' ],
            ['nombre'=>'Huehuetán','clave'=> '037' ],
            ['nombre'=>'Huixtán','clave'=> '038' ],
            ['nombre'=>'Huitiupán','clave'=> '039' ],
            ['nombre'=>'Huixtla','clave'=> '040' ],
            ['nombre'=>'La Independencia','clave'=> '041' ],
            ['nombre'=>'Ixhuatán','clave'=> '042' ],
            ['nombre'=>'Ixtacomitán','clave'=> '043' ],
            ['nombre'=>'Ixtapa','clave'=> '044' ],
            ['nombre'=>'Ixtapangajoya','clave'=> '045' ],
            ['nombre'=>'Jiquipilas','clave'=> '046' ],
            ['nombre'=>'Jitotol','clave'=> '047' ],
            ['nombre'=>'Juárez','clave'=> '048' ],
            ['nombre'=>'Larráinzar','clave'=> '049' ],
            ['nombre'=>'La Libertad','clave'=> '050' ],
            ['nombre'=>'Mapastepec','clave'=> '051' ],
            ['nombre'=>'Las Margaritas','clave'=>'052' ],
            ['nombre'=>'Mazapa de Madero','clave'=>'053' ],
            ['nombre'=>'Mazatán','clave'=>'054' ],
            ['nombre'=>'Metapa','clave'=>'055' ],
            ['nombre'=>'Mitontic','clave'=>'056' ],
            ['nombre'=>'Motozintla','clave'=>'057' ],
            ['nombre'=>'Nicolás Ruíz','clave'=>'058' ],
            ['nombre'=>'Ocosingo','clave'=>'059' ],
            ['nombre'=>'Ocotepec','clave'=>'060' ],
            ['nombre'=>'Ocozocoautla de Espinosa','clave'=>'061' ],
            ['nombre'=>'Ostuacán','clave'=>'062' ],
            ['nombre'=>'Osumacinta','clave'=>'063' ],
            ['nombre'=>'Oxchuc','clave'=>'064' ],
            ['nombre'=>'Palenque','clave'=>'065' ],
            ['nombre'=>'Pantelhó','clave'=>'066' ],
            ['nombre'=>'Pantepec','clave'=>'067' ],
            ['nombre'=>'Pichucalco','clave'=>'068' ],
            ['nombre'=>'Pijijiapan','clave'=>'069' ],
            ['nombre'=>'El Porvenir','clave'=>'070' ],
            ['nombre'=>'Villa Comaltitlán','clave'=>'071' ],
            ['nombre'=>'Pueblo Nuevo Solistahuacán','clave'=>'072' ],
            ['nombre'=>'Rayón','clave'=>'073' ],
            ['nombre'=>'Reforma','clave'=>'074' ],
            ['nombre'=>'Las Rosas','clave'=>'075' ],
            ['nombre'=>'Sabanilla','clave'=>'076' ],
            ['nombre'=>'Salto de Agua','clave'=>'077' ],
            ['nombre'=>'San Cristóbal de las Casas','clave'=>'078' ],
            ['nombre'=>'San Fernando','clave'=>'079' ],
            ['nombre'=>'Siltepec','clave'=>'080' ],
            ['nombre'=>'Simojovel','clave'=>'081' ],
            ['nombre'=>'Sitalá','clave'=>'082' ],
            ['nombre'=>'Socoltenango','clave'=>'083' ],
            ['nombre'=>'Solosuchiapa','clave'=>'084' ],
            ['nombre'=>'Soyaló','clave'=>'085' ],
            ['nombre'=>'Suchiapa','clave'=>'086' ],
            ['nombre'=>'Suchiate','clave'=>'087' ],
            ['nombre'=>'Sunuapa','clave'=>'088' ],
            ['nombre'=>'Tapachula','clave'=>'089' ],
            ['nombre'=>'Tapalapa','clave'=>'090' ],
            ['nombre'=>'Tapilula','clave'=>'091' ],
            ['nombre'=>'Tecpatán','clave'=>'092' ],
            ['nombre'=>'Tenejapa','clave'=>'093' ],
            ['nombre'=>'Teopisca','clave'=>'094' ],
            ['nombre'=>'Tila','clave'=>'095' ],
            ['nombre'=>'Tonalá','clave'=>'096' ],
            ['nombre'=>'Totolapa','clave'=>'097' ],
            ['nombre'=>'La Trinitaria','clave'=>'098' ],
            ['nombre'=>'Tumbalá','clave'=>'099' ],
            ['nombre'=>'Tuxtla Gutiérrez','clave'=>'100' ],
            ['nombre'=>'Tuxtla Chico','clave'=>'101' ],
            ['nombre'=>'Tuzantán','clave'=>'102' ],
            ['nombre'=>'Tzimol','clave'=>'103' ],
            ['nombre'=>'Unión Juárez','clave'=>'104' ],
            ['nombre'=>'Venustiano Carranza','clave'=>'105' ],
            ['nombre'=>'Villa Corzo','clave'=>'106' ],
            ['nombre'=>'Villaflores','clave'=>'107' ],
            ['nombre'=>'Yajalón','clave'=>'108' ],
            ['nombre'=>'San Lucas','clave'=>'109' ],
            ['nombre'=>'Zinacantán','clave'=>'110' ],
            ['nombre'=>'San Juan Cancuc','clave'=>'111' ],
            ['nombre'=>'Aldama','clave'=>'112' ],
            ['nombre'=>'Benemérito de las Américas','clave'=>'113' ],
            ['nombre'=>'Maravilla Tenejapa','clave'=>'114' ],
            ['nombre'=>'Marqués de Comillas','clave'=>'115' ],
            ['nombre'=>'Montecristo de Guerrero','clave'=>'116' ],
            ['nombre'=>'San Andrés Duraznal','clave'=>'117' ],
            ['nombre'=>'Santiago el Pinar','clave'=>'118' ],
            ['nombre'=>'Capitán Luis Ángel Vidal','clave'=>'119' ],
            ['nombre'=>'Rincón Chamula San Pedro','clave'=>'120' ],
            ['nombre'=>'El Parral','clave'=>'121' ],
            ['nombre'=>'Emiliano Zapata','clave'=>'122' ],
            ['nombre'=>'Mezcalapa','clave'=>'123' ],
            ['nombre'=>'Honduras de la Sierra','clave'=>'124' ]
        ]);
    }
}
